spring:
  application:
    name: client-app
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9001"
      client:
        registration:
          client-app:
            provider: my-provider
            client-id: client-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope:
              - openid
              - profile
              - read
              - write
            client-name: client-app
        provider: #issuer-uri: https://my-auth-server.com
          my-provider:
            issuer-uri: "http://127.0.0.1:9001"
           
#logging:
 # level:
  #  org:
   #   springframework:
    #    security: DEBUG  # Enable DEBUG level logging for Spring Security
